Ревью спринт 3 попытка 5
oldcyber/ya-devops-1 pull request #18
Opened 2022-10-05 17:03 UTC by oldcyber

2022-10-12 16:08 UTC, tmvrus requested changes
- строки "gauge" и "counter" должны быть константами, это повысит читаемость кода и избавит от дублирования

- закомментированный код нужно либо удалить, либо раскомментировать

2022-10-12 16:08 UTC, tmvrus commented on internal/tools/config.go
> +	// DatabaseDSN    string        `env:"DATABASE_DSN" envDefault:"postgres://postgres:postgrespw@localhost:55001/praktikum?sslmode=disable"`
Такие комментарии засоряют код, их следует избегать.

2022-10-12 16:08 UTC, tmvrus commented on internal/mydata/counterdata.go
> +package mydata
`mydata ` крайне неудачно название для пакета, поскольку ничего не говорит о своем содержимом, здесь больше подойдет storage, store и тп

2022-10-12 16:08 UTC, tmvrus commented on internal/mydata/dbstoredata.go
> +//func (ms *DBStoreData) AddNewItem(db *sql.DB, res []string) (bool, int) {
комментарии такого рода засоряют кода и усложняют его восприятие

2022-10-12 16:08 UTC, tmvrus commented on internal/mydata/counterdata.go
> +package mydata
в go принято использовать underscore naming для файлов, counterdata.go -> counter_data.go и тд

2022-10-12 16:08 UTC, tmvrus commented on internal/mydata/dbstoredata.go
> +func (ms *DBStoreData) AddNewItem(res []string) (bool, int) {
у этой ф-и крайне неудачный дизайн, она возвращает http-коды ошибок, это называется "Leaky Abstractions", в данном случае storage-layer используют значения из transport-layer, таких ситуаций нужно избегать

2022-10-13 15:00 UTC, oldcyber commented on internal/mydata/dbstoredata.go
> +func (ms *DBStoreData) AddNewItem(res []string) (bool, int) {
Пропустил. Думал везде изменил.

2022-10-13 15:08 UTC, oldcyber commented
> * строки "gauge" и "counter" должны быть константами, это повысит читаемость кода и избавит от дублирования
> * закомментированный код нужно либо удалить, либо раскомментировать

Не могу понять где у меня такие строки? У меня есть два типа: gauge и counter

2022-10-13 16:36 UTC, tmvrus requested changes
Требование очистить проект от закомметированного кода проигнорировано.

2022-10-13 16:36 UTC, tmvrus commented on internal/storage/storeddata.go
> +	case "gauge":
вот эти строки должны быть константами

2022-10-14 06:23 UTC, oldcyber commented
> Требование очистить проект от закомметированного кода проигнорировано.

Не проигнорированы, а выполнено не в полном объёме ☺️ Сейчас прошёлся ещё раз по всем файлам проекта. Оставил только пояснения по коду

2022-10-14 06:37 UTC, oldcyber commented on internal/storage/storeddata.go
> +	case "gauge":
Простите, может у меня уже альцгеймер или ещё какое старческое заболевание развивается, но я в упор не вижу что в свиче можно сделать константой??? Способ хранения я себе конечно кособокий придумал, но вроде там всё логично? Нужно больше информации! Или пояснения что типа по канону? делают вот так-то и так-то, почитать тут:[URL]

2022-10-17 16:19 UTC, tmvrus requested changes

2022-10-17 16:19 UTC, tmvrus commented on cmd/server/main.go
> +		}
закоментированный код

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/jsondata.go
> +		// хз почему без промежуточного объявления все Value получали одинаковое значения
потому что так работают циклы в Go,
https://practicum-students.slack.com/archives/C0424HXF9P0/p1665994496099219

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/jsondata.go
> +	rawBytes = append(rawBytes, ']')
Зачем весь этот код с for/append ? Почему нельзя просто вот так:
```
rawBytes , err := easyjson.Marshal(metrics)
```
?

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/metricdata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/metricdata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/agent/sender_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/agent/sender_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/agent/sender_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/agent/sender_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) AddNewItem(res []string) (bool, int) {
не соответствует https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r993656509

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) GetStoredDataByName(mType, mName string) (string, int) {
не соответствует https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r993656509

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) GetStoredDataByParamToJSON(m Metrics, key string) ([]byte, int) {
не соответствует https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r993656509

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata.go
> +func (sd *StoredData) AddNewItem(res []string) (bool, int) {
не соответствует https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r993656509

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata.go
> +func (sd *StoredData) GetStoredDataByParamToJSON(m Metrics, key string) ([]byte, int) {
не соответствует https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r993656509

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata.go
> +func (sd *StoredData) GetStoredDataByName(mtype, mname string) (string, int) {
не соответствует https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r993656509

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata_test.go
> +		// TODO: Add test cases.
нужно добавить тесткейс и убрать комментарий

2022-10-17 16:19 UTC, tmvrus commented on internal/storage/storeddata.go
> +	case "gauge":
Не стоит аппелировать к медицинским диагнозам, это лишнее. В индустрии есть такое понятие как "magic constant", пример с числами хорошо разобран [вот тут](https://ru.hexlet.io/blog/posts/magic-numbers)
Со строками -  все тоже самое.

**Если возникает вопрос, недопонимание или уточнение всегда можно на писать в slack: задать вопрос или получить 1-1.**

2022-10-18 11:42 UTC, oldcyber commented on internal/mydata/dbstoredata.go
> +func (ms *DBStoreData) AddNewItem(res []string) (bool, int) {
Ссылка ведёт в вникуда

2022-10-18 11:47 UTC, oldcyber commented on cmd/server/main.go
> +		}
Потому что будет ошибка: Cannot use 'metrics' (type []Metrics) as the type Marshaler Type does not implement 'Marshaler' as some methods are missing: MarshalEasyJSON(w *jwriter.Writer)

2022-10-18 12:02 UTC, oldcyber commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) AddNewItem(res []string) (bool, int) {
Используется для читаемости кода. Буду возвращать просто число но смысл от этого не изменится. Кстати такое решение мне подсказал один из преподавателей.

2022-10-18 12:02 UTC, oldcyber commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) GetStoredDataByName(mType, mName string) (string, int) {
Используется для читаемости кода. Буду возвращать просто число но смысл от этого не изменится. Кстати такое решение мне подсказал один из преподавателей.

2022-10-18 12:02 UTC, oldcyber commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) GetStoredDataByParamToJSON(m Metrics, key string) ([]byte, int) {
Используется для читаемости кода. Буду возвращать просто число но смысл от этого не изменится. Кстати такое решение мне подсказал один из преподавателей.

2022-10-18 12:02 UTC, oldcyber commented on internal/storage/storeddata.go
> +func (sd *StoredData) GetStoredDataByParamToJSON(m Metrics, key string) ([]byte, int) {
Используется для читаемости кода. Буду возвращать просто число но смысл от этого не изменится. Кстати такое решение мне подсказал один из преподавателей.

2022-10-18 12:03 UTC, oldcyber commented on internal/storage/storeddata.go
> +func (sd *StoredData) GetStoredDataByName(mtype, mname string) (string, int) {
Используется для читаемости кода. Буду возвращать просто число но смысл от этого не изменится. Кстати такое решение мне подсказал один из преподавателей.

2022-10-18 12:03 UTC, oldcyber commented on internal/storage/storeddata.go
> +func (sd *StoredData) AddNewItem(res []string) (bool, int) {
Используется для читаемости кода. Буду возвращать просто число но смысл от этого не изменится. Кстати такое решение мне подсказал один из преподавателей.

2022-10-18 12:28 UTC, tmvrus commented on cmd/server/main.go
> +		}
Если будет ошибка, ее надо обработать

2022-10-18 12:30 UTC, tmvrus commented on internal/storage/dbstoredata.go
> +func (ms *DBStoreData) AddNewItem(res []string) (bool, int) {
Спорное утверждение, лично я вижу что возвращаются http-статусы из storage-layer,  я такой код не приму, даже если кто-то порекомендовал так сделать.

2022-10-18 15:50 UTC, oldcyber commented on cmd/server/main.go
> +		}
Так. Это комментарий должен был быть к другой части кода. Здесь всё исправлено

2022-10-18 15:52 UTC, oldcyber commented on internal/storage/jsondata.go
> +	rawBytes = append(rawBytes, ']')
Там посылается строка странного вида в [] и ещё обязательно после последнего значения должна быть запятая. Поэтому такая конструкция.

2022-10-20 17:20 UTC, tmvrus requested changes
Мы третий раз это обсуждаем
https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r997267164

2022-10-20 17:28 UTC, oldcyber commented
> Мы третий раз это обсуждаем
> [#18 (comment)](https://github.com/oldcyber/ya-devops-1/pull/18#discussion_r997267164)

Так я ж добавил константы??? 49 и 50 строка в storeddata.go

2022-10-24 20:23 UTC, tmvrus approved these changes
Есть мелкие недочеты, некритично.

2022-10-24 20:23 UTC, tmvrus commented on cmd/server/main.go
> +	readHeaderTimeout = 3
константа может быть вполне с типом time.Duration и ее не нужно будет в последствии приводить,
readHeaderTimeout = time.Second*3

2022-10-24 20:23 UTC, tmvrus commented on cmd/server/main.go
> +			panic(err)
log.Fatal сделает все тоже самое

2022-10-24 20:23 UTC, tmvrus commented on internal/server/hash.go
> +func calcHash(cfg config, m storage.Metrics) string {
есть еще ф-я CountHash, с виду делает тоже самое, возможно хватит одной ф-и что бы вычислять хеш

2022-10-27 14:35 UTC, merged